version: '3.1'
services:
  facade:
    image: "iot:hue-facade"
    ports:
      - "8083:8080"
    build:
      context: ./facade
      args:
        JAR_FILE: philips-hue-api-facade-thorntail.jar
        PORT_NUMBER: 8080
    secrets:
      - huecredentials
    external_links:
      - jaeger
    networks:
      - default
      - jaeger-net
  timeservice:
    image: "iot:time-service"
    ports:
      - "9081:8080"
    build:
      context: ./timeservice
      args:
        JAR_FILE: timeservice-thorntail.jar
        PORT_NUMBER: 8080
    external_links:
    - jaeger
    networks:
    - default
    - jaeger-net
  weatherservice:
    image: "iot:weather-service"
    ports:
      - "8082:8080"
    build:
      context: ./weatherservice
      args:
        JAR_FILE: weatherservice-thorntail.jar
        PORT_NUMBER: 8080
        JVM_OPTIONS: -Dcountry=Moldova -Dyr_city_part=Chisinau/Chişinău
    external_links:
    - jaeger
    networks:
    - default
    - jaeger-net
networks:
  jaeger-net:
    external: true
secrets:
  huecredentials:
    file: ./facade/MyHue.properties