version: '3.1'
services:
  facade:
    image: "iot:hue-facade"
    ports:
      - "8083:8080"
    build:
      context: ./facade
      args:
        JAR_FILE: philips-hue-api-facade-thorntail.jar
        PORT_NUMBER: 8080
        TIMEZONE: Europe/Kiev
    secrets:
      - huecredentials
  timeservice:
    image: "iot:time-service"
    ports:
      - "9081:8080"
    build:
      context: ./timeservice-v2
      args:
        JAR_FILE: timeservice-thorntail.jar
        PORT_NUMBER: 8080
        TIMEZONE: Europe/Oslo
  weatherservice:
    image: "iot:weather-service"
    ports:
      - "8082:8080"
    build:
      context: ./weatherservice
      args:
        JAR_FILE: weatherservice-thorntail.jar
        PORT_NUMBER: 8080
        JVM_OPTIONS: -Dcountry=Ukraina -Dyr_city_part=Kiev/Kiev
        TIMEZONE: Europe/Kiev
secrets:
  huecredentials:
    file: ./facade/MyHue.properties