apiVersion: v1
kind: Service
metadata:
 annotations:
  service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
 name: gateway
 labels:
  app: gateway
spec:
 type: NodePort
 ports:
 - port: 8080
   name: gateway
   targetPort: 8080
   nodePort: 32759
 selector:
  app: gateway

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: gateway
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: gateway
  spec:
   hostname: gateway
   subdomain: microprofile-iot
   containers:
   - name: gateway
     image: iot:gateway
     env:
     - name: PORT_NUMBER
       value: '8080'
     - name: CONTEXT
       value: ./hueAPI
     - name: JAR_FILE
       value: gateway-swarm.jar
     ports:
      - containerPort: 8080