apiVersion: v1
kind: Service
metadata:
 annotations:
  service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
 name: time-service
 labels:
  app: time-service
spec:
 type: NodePort
 ports:
 - port: 8080
   name: time-service
   targetPort: 8080
   nodePort: 32757
 selector:
  app: time-service

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: time-service
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: time-service
  spec:
   containers:
   - name: time-service
     image: iot:time-service
     env:
     - name: PORT_NUMBER
       value: '8080'
     - name: CONTEXT
       value: ./hueAPI
     - name: JAR_FILE
       value: timeservice-swarm.jar
     ports:
      - containerPort: 8080