apiVersion: v1
kind: Service
metadata:
 annotations:
  service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
 name: hue-facade
 labels:
  app: hue-facade
spec:
 type: NodePort
 ports:
 - port: 8080
   name: hue-facade
   targetPort: 8080
   nodePort: 32756
 selector:
  app: hue-facade

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: hue-facade
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: hue-facade
  spec:
   containers:
   - name: hue-facade
     image: iot:hue-facade
     env:
     - name: PORT_NUMBER
       value: '8080'
     - name: CONTEXT
       value: ./hueAPI
     - name: JAR_FILE
       value: philips-hue-api-swarm.jar
     ports:
      - containerPort: 8080